name: webCrawler

on: 
  schedule:
    - cron: '*/10 18,23,5 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    - name: execute py script # run main.py
      env:
        DSA_SHEET: ${{ secrets.DSA_SHEET }}
      run: python nchu_mis.py

